### ISSUE TITLE
'Access Denied' at first access

### ISSUE THREAD

**Issue by MajorDeew** [gentee/eonza#6]
Hi,

Eonza keeps return me 'Access Denied' after first installation.

OS: Linux server 4.15.0-137-generic #141-Ubuntu SMP
Eonza web page hosted by: Apache 2.4.29 reverse proxy

Eonza config:
```
mode: default
assetsdir: ""
packagesdir: ""
log:
    dir: ""
    mode: file
    level: info
users:
    dir: ""
http:
    host: localhost
    port: 9500
    localport: 0
    open: false
    theme: default
    jwtkey: b3j5yqphe5zh
    cert: ""
    priv: ""
playground:
    dir: ""
    summary: 0
    files: 0
    size: 0
    tasks: 0
whitelist:
    - 127.0.0.1/31
    - 192.168.0.0/23
    - <a public ip>
```

Apache VirtualServer config:
```
<IfModule mod_ssl.c>
	<VirtualHost 192.168.0.10:443>
		ServerAdmin tiozzoluca98@gmail.com
		ServerName tools.majordevelop.it

		DocumentRoot /var/www/html/tools/
	

		ProxyPass /scripts http://127.0.0.1:9500/
		ProxyPassReverse /scripts http://127.0.0.1:9500/
		ProxyPass /.well-known/ !
		
		ProxyPreserveHost On
		
		
		RequestHeader set X-Forwarded-Proto https
		RequestHeader set X-Forwarded-Ssl on
		RequestHeader set X-Url-Scheme https
		
		
		Protocols h2 http/1.1

		
		BrowserMatch "MSIE [2-6]" \
			nokeepalive ssl-unclean-shutdown \
			downgrade-1.0 force-response-1.0
			
		
		SSLEngine On
                
		Include /etc/letsencrypt/options-ssl-apache.conf
		SSLCertificateFile /etc/letsencrypt/live/tools.majordevelop.it/fullchain.pem
		SSLCertificateKeyFile /etc/letsencrypt/live/tools.majordevelop.it/privkey.pem
		
		SSLCipherSuite HIGH:RC4-SHA:AES128-SHA:!aNULL:!MD5
		SSLHonorCipherOrder on

		SSLProtocol all -SSLv2 -SSLv3 -TLSv1 -TLSv1.1
		
		
		<FilesMatch ".(cgi|shtml|phtml|php)$">
				SSLOptions +StdEnvVars
		</FilesMatch>

		<Directory /usr/lib/cgi-bin>
				SSLOptions +StdEnvVars
		</Directory>	
	</VirtualHost>
</IfModule>

<VirtualHost 192.168.0.10:80>
	ServerName tools.majordevelop.it

	RewriteEngine On
	RewriteCond %{HTTPS} off
	RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]

	ErrorLog /var/log/apache2/redirect.error.log
	LogLevel warn
</VirtualHost>
```

After installation (./eonza -install -psw=mypassword) and starting systemd service, the socket 127.0.0.1:9500 stay in listening but every times I try to reach tools.majordevelop.it/scripts the page return me 403 with Json 'message: Access denied'.

I installed Eonza in /opt/eonza, created user eonza and give permission rwx to /opt/eonza.

Permission:
```
total 23M
drwxr-xr-x  4 eonza eonza 4,0K lug 13 14:10 .
drwxr-xr-x 12 root  root  4,0K lug 13 10:01 ..
-rwxrwxr-x  1 eonza eonza  23M lug 13 10:00 eonza
-rwxr-xr-x  1 eonza eonza  440 lug 13 12:43 eonza.eon
-rwxr-xr-x  1 eonza eonza 6,2K lug 13 11:58 eonza.eox
-rwxr-xr-x  1 eonza eonza  404 lug 13 14:10 eonza.yaml
drwxr-xr-x  2 eonza eonza 4,0K lug 13 11:58 log
drwxr-xr-x  2 eonza eonza 4,0K lug 13 11:58 users
```

**Comment by gentee** [comment]
I have not used eonza with a reverse proxy. 
Try to change ProxyPass & ProxyPassReverse as
ProxyPass /scripts http://localhost:9500/
ProxyPassReverse /scripts http://localhost:9500/
Because, you specified http->host as localhost in the eonza config.

Also, tools.majordevelop.it/scripts/cmd must be redirected to  http://localhost:9500/cmd.
Is there such redirection now?
For example,
tools.majordevelop.it/scripts/ping => http://localhost:9500/ping

**Comment by MajorDeew** [comment]
I have added redirect now for cmd after slash and changed 127.0.0.1 to localhost:
```
ProxyPass /scripts http://localhost:9500/
ProxyPassReverse /scripts http://localhost:9500/
ProxyPass /scripts/(.*) http://localhost:9500/$1
ProxyPassReverse /scripts/(.*) http://localhost:9500/$1
```

but it still doesn't work.

The json message 'message:Access denied' is returned by Eonza throught apache, not apache itself, so I think the reverse proxy is working fine.


Other tests or config I can try?


Thanks, and sorry for my bad english :P

**Comment by MajorDeew** [comment]
Also I have tried to remove whitelist or insert my public specific client IP, nothing works.

**Comment by gentee** [comment]
Eonza tries to get a real ip address and matches it with Whitelist. May be Apache send a request with ip that it is not in the white list. Try to remove a whitelist block from eonza.yaml and restart eonza. If it will work then we need to know that ip and append it to whitelist. For example, I recommend to insert   ::1/128 in whitelist.
Have you compiled eonza yourself or downloaded a compiled version?

**Comment by MajorDeew** [comment]
i've downloaded compiled version, in tar.gz and elf file. I didn't saw uncompiled version..

Anyway i removed whitelist block, still not working:

![ezgif-2-ac13331b13](https://user-images.githubusercontent.com/18647340/178750691-69724a20-5d7d-490d-b1f5-d191b45cbab5.gif)

**Comment by gentee** [comment]
I will try to do the same on my hosting and let you know in 2-3 days.

**Comment by gentee** [comment]
I have looked at the problem more details. Unfortunately, it is impossible to redirect path to eonza because eonza loads resources files (js, css) from the root folder. 
You open domain.com/scripts but eonza tries to load domain.com/js, domain.com/css etc.

The right way is to specify eonza.yaml like this

```
mode: default
assetsdir: ""
packagesdir: ""
log:
    dir: ""
    mode: file
    level: info
users:
    dir: ""
http:
    host: tools.majordevelop.it
    port: 9500
    open: false
    theme: default
    jwtkey: your_jwt_key
    cert: "/etc/letsencrypt/live/tools.majordevelop.it/fullchain.pem"
    priv: "/etc/letsencrypt/live/tools.majordevelop.it/privkey.pem"
whitelist:
  - ::1/128
  - 127.0.0.0/31
  - 192.168.0.0/23
  - <your computer IP>
```
and use Eonza without Apache proxy as https://tools.majordevelop.it:9500.

In the whitelist, you should specify the IP (or mask) of your computer where you open Eonza in browser.
